dist: bionic
language: python

matrix:
    include:
      - python: 3.6.12
        env: TOX_ENV=py36
      - python: 3.7.9
        env: TOX_ENV=py37
      - python: 3.8.6
        env: TOX_ENV=py38
      - python: 3.9.1
        env: TOX_ENV=py39
      - python: pypy3
        env: TOX_ENV=pypy3
      - python: 3.9.1
        env: TOX_ENV=lint

install:
  - pip install -U -r requirements-dev.txt
  - pip install .

script:
  - tox -e $TOX_ENV
  - pytest --dead-fixtures

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
