dist: xenial
language: python

matrix:
    include:
      - python: 3.5.7
        env: TOX_ENV=py35
      - python: 3.6.8
        env: TOX_ENV=py36
      - python: 3.7.3
        env: TOX_ENV=py37
      - python: pypy
        env: TOX_ENV=pypy
      - python: 3.7.3
        env: TOX_ENV=lint

install:
  - pip install -U -r requirements-dev.txt
  - pip install .

script:
  - tox -e $TOX_ENV
  - pytest --dead-fixtures

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
